# Priority
- name: 'priority: critical'
  color: 'e11d21'
  description: 'Critical priority issue'
- name: 'priority: high'
  color: 'eb6420'
  description: 'High priority issue'
- name: 'priority: medium'
  color: 'fbca04'
  description: 'Medium priority issue'
- name: 'priority: low'
  color: '009800'
  description: 'Low priority issue'

# Type
- name: 'type: bug'
  color: 'd73a4a'
  description: 'Something is not working'
- name: 'type: feature'
  color: 'a2eeef'
  description: 'New feature or request'
- name: 'type: enhancement'
  color: '84b6eb'
  description: 'Enhancement to existing feature'
- name: 'type: documentation'
  color: '0075ca'
  description: 'Improvements or additions to documentation'
- name: 'type: security'
  color: 'ee0701'
  description: 'Security vulnerability or concern'
- name: 'type: performance'
  color: 'ffb347'
  description: 'Performance improvement'

# Component
- name: 'component: frontend'
  color: '7057ff'
  description: 'Frontend related'
- name: 'component: backend'
  color: '008672'
  description: 'Backend related'
- name: 'component: ai'
  color: 'ffd700'
  description: 'AI/ML related'
- name: 'component: websocket'
  color: '006b75'
  description: 'WebSocket related'
- name: 'component: chart'
  color: 'ff6b6b'
  description: 'Chart component related'

# Status
- name: 'status: needs review'
  color: 'ffffff'
  description: 'Needs code review'
- name: 'status: in progress'
  color: 'ededed'
  description: 'Work in progress'
- name: 'status: blocked'
  color: 'e11d21'
  description: 'Blocked by another issue'
- name: 'status: ready'
  color: '0e8a16'
  description: 'Ready to be worked on'

# Other
- name: 'good first issue'
  color: '7057ff'
  description: 'Good for newcomers'
- name: 'help wanted'
  color: '008672'
  description: 'Extra attention is needed'
- name: 'dependencies'
  color: '0366d6'
  description: 'Pull requests that update a dependency file'
