name: goldensignalsai-py311
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      # Poetry manages Python dependencies; environment.yaml is only for creating the base env
      - poetry
