#!/bin/bash

echo "This script will help you fix the Git history containing secrets"
echo ""
echo "You have 3 options:"
echo ""
echo "Option 1: Allow the secrets (if they're test keys)"
echo "Visit these URLs in your browser:"
echo "  - OpenAI: https://github.com/isaacbuz/GoldenSignalsAIv4/security/secret-scanning/unblock-secret/30HnRdG3C68vLcHxPxMmNSnIrZC"
echo "  - Anthropic: https://github.com/isaacbuz/GoldenSignalsAIv4/security/secret-scanning/unblock-secret/30HnRevuXH7bu7zRtn8EdRKVGsJ"
echo "  - xAI: https://github.com/isaacbuz/GoldenSignalsAIv4/security/secret-scanning/unblock-secret/30HnRbsUId1SZuSs4K6oy4erJYI"
echo ""
echo "Option 2: Remove secrets from history (recommended for real keys)"
echo "Run: git filter-branch --force --index-filter 'git rm --cached --ignore-unmatch .env' --prune-empty --tag-name-filter cat -- --all"
echo ""
echo "Option 3: Start fresh (nuclear option)"
echo "1. Back up your current work"
echo "2. Create a new branch without the problematic commit"
echo "3. Cherry-pick only the commits you want to keep"
echo ""
echo "After choosing an option, you can push with:"
echo "git push origin main --force"
