global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules
rule_files:
  - "rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # MCP Servers
  - job_name: 'mcp-servers'
    static_configs:
      - targets:
          - 'market-data-mcp:8190'
          - 'rag-query-mcp:8191'
          - 'agent-comm-mcp:8192'
          - 'risk-analytics-mcp:8193'
          - 'execution-mcp:8194'
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Integration test metrics
  - job_name: 'integration-tests'
    static_configs:
      - targets: ['integration-tests:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s
