groups:
  - name: goldensignalsai-alerts
    rules:
      - alert: BackendDown
        expr: up{job="goldensignalsai-backend"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Backend is down"
          description: "No response from FastAPI backend for 1 minute."
