# Model hyperparameters
models:
  lstm:
    sequence_length: 50
    features: 1
    hidden_units: 64
    epochs: 20
    batch_size: 32
  xgboost:
    params:
      objective: reg:squarederror
    num_round: 100
  lightgbm:
    params:
      objective: regression
    num_round: 100

# Strategy parameters
strategies:
  moving_average_crossover:
    short_window: 20
    long_window: 50
  rsi_strategy:
    lower: 30
    upper: 70
  atr_breakout:
    period: 14
    multiplier: 2

# Thresholds (per symbol, per strategy if desired)
thresholds:
  AAPL:
    base: 1.5
    atr_mult: 2.0
  TSLA:
    base: 2.0
    atr_mult: 2.5
  default:
    base: 1.0
    atr_mult: 2.0
