apiVersion: v1
kind: Namespace
metadata:
  name: goldensignals
  labels:
    name: goldensignals
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: goldensignals-quota
  namespace: goldensignals
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 40Gi
    limits.cpu: "40"
    limits.memory: 80Gi
    persistentvolumeclaims: "10"
    services: "20"
    pods: "50"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: goldensignals-limits
  namespace: goldensignals
spec:
  limits:
  - max:
      cpu: "4"
      memory: 8Gi
    min:
      cpu: 100m
      memory: 128Mi
    default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 250m
      memory: 256Mi
    type: Container
