name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: AI Code Review
        uses: coderabbitai/ai-pr-reviewer@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          debug: false
          review_simple_changes: false
          review_comment_lgtm: false
          openai_light_model: gpt-4
          openai_heavy_model: gpt-4-turbo-preview
          openai_timeout_ms: 900000
          language: en
          system_message: |
            You are an expert code reviewer for a FinTech trading signals application.
            Focus on:
            - Security vulnerabilities
            - Performance optimizations
            - React/TypeScript best practices
            - Python/FastAPI patterns
            - WebSocket stability
            - Real-time data handling
          summarize: |
            Provide a concise summary of the changes and highlight any:
            - Breaking changes
            - Security concerns
            - Performance impacts
            - Required migrations
          summarize_release_notes: |
            Create release notes in the following format:
            ### Features
            ### Bug Fixes
            ### Performance
            ### Breaking Changes
